---
galaxy_info:
  role_name: neovim
  namespace: petzko
  author: petzko
  description: "Install Neovim + the AstroNvim distribution and shell integration."
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Archlinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - neovim
    - editor
    - dotfiles

dependencies: []
