---
galaxy_info:
  role_name: libreoffice
  namespace: petzko
  author: petzko
  description: "Install the LibreOffice desktop office suite."
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - libreoffice
    - office
    - productivity
    - dotfiles

dependencies: []
