---
galaxy_info:
  role_name: docker
  namespace: petzko
  author: petzko
  description: "Install Docker Engine + Compose and enable the daemon."
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Archlinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - docker
    - containers
    - dotfiles

dependencies: []
